config/routes.rb
Rails.application.routes.draw do
  mount Lockup::Engine, at: '/lockup'
  resources :real_accounts
  resources :smurves
  get "/home" => "pages#show", page: "home"
  get "/about" => "pages#show", page: "about"
  #this should be the last route
  root "pages#show", page: "home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/real_account.rb
class RealAccount < ApplicationRecord
end

app/models/smurf.rb
class Smurf < ApplicationRecord
  scope :process, -> { where(status: 'process') }
  scope :warmup, -> { where(status: 'warmup') }
  scope :active, -> { where(status: 'active') }
  default_scope { order(status: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
  include Authenticate::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticate::Controller
  before_action :require_login
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    if valid_page?
      render template: "pages/#{params[:page]}"
      else
      render file: "public/404.html", status: :not_found
    end
  end
  
  private
  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
  end
end

app/controllers/real_accounts_controller.rb
class RealAccountsController < ApplicationController
  before_action :set_real_account, only: [:show, :edit, :update, :destroy]

  # GET /real_accounts
  # GET /real_accounts.json
  def index
    @real_accounts = RealAccount.all
  end

  # GET /real_accounts/1
  # GET /real_accounts/1.json
  def show
  end

  # GET /real_accounts/new
  def new
    @real_account = RealAccount.new
  end

  # GET /real_accounts/1/edit
  def edit
  end

  # POST /real_accounts
  # POST /real_accounts.json
  def create
    @real_account = RealAccount.new(real_account_params)

    respond_to do |format|
      if @real_account.save
        format.html { redirect_to @real_account, notice: 'Real account was successfully created.' }
        format.json { render :show, status: :created, location: @real_account }
      else
        format.html { render :new }
        format.json { render json: @real_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /real_accounts/1
  # PATCH/PUT /real_accounts/1.json
  def update
    respond_to do |format|
      if @real_account.update(real_account_params)
        format.html { redirect_to @real_account, notice: 'Real account was successfully updated.' }
        format.json { render :show, status: :ok, location: @real_account }
      else
        format.html { render :edit }
        format.json { render json: @real_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /real_accounts/1
  # DELETE /real_accounts/1.json
  def destroy
    @real_account.destroy
    respond_to do |format|
      format.html { redirect_to real_accounts_url, notice: 'Real account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_real_account
      @real_account = RealAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def real_account_params
      params.require(:real_account).permit(:startdate, :ip, :firstname, :lastname, :fb_email, :fb_pw, :fb_profile_link, :paypal_email, :referrer_paypal, :phone, :disbursement_date, :disbursement_amount, :skype_username, :notes)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Authenticate::SessionController
  # render sign in screen
  def new
    # ...
  end

  def destroy
    logout
    redirect_to '/', notice: 'You logged out successfully'
  end
end

app/controllers/smurves_controller.rb
class SmurvesController < ApplicationController
  before_action :set_smurf, only: [:show, :edit, :update, :destroy]

  # GET /smurves
  # GET /smurves.json
  def index
    @smurves = Smurf.all
  end

  # GET /smurves/1
  # GET /smurves/1.json
  def show
  end

  # GET /smurves/new
  def new
    @smurf = Smurf.new
  end

  # GET /smurves/1/edit
  def edit
  end

  # POST /smurves
  # POST /smurves.json
  def create
    @smurf = Smurf.new(smurf_params)

    respond_to do |format|
      if @smurf.save
        format.html { redirect_to @smurf, notice: 'Smurf was successfully created.' }
        format.json { render :show, status: :created, location: @smurf }
      else
        format.html { render :new }
        format.json { render json: @smurf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smurves/1
  # PATCH/PUT /smurves/1.json
  def update
    respond_to do |format|
      if @smurf.update(smurf_params)
        format.html { redirect_to @smurf, notice: 'Smurf was successfully updated.' }
        format.json { render :show, status: :ok, location: @smurf }
      else
        format.html { render :edit }
        format.json { render json: @smurf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smurves/1
  # DELETE /smurves/1.json
  def destroy
    @smurf.destroy
    respond_to do |format|
      format.html { redirect_to smurves_url, notice: 'Smurf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_smurf
      @smurf = Smurf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def smurf_params
      params.require(:smurf).permit(:startdate, :status, :ip, :firstname, :lastname, :login, :password, :cardtype, :creditcardnumber, :email, :paypalemail, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/real_accounts_helper.rb
module RealAccountsHelper
end

app/helpers/smurves_helper.rb
module SmurvesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomoresheets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= nav_bar responsive: true, brand: "Brand Ambassadors" do %>
      <%= menu_group do %>
          <%= menu_item "Smurves", smurves_path %>
          <%= menu_item "Real Accounts", real_accounts_path %>
          <%= menu_item "About Us", about_path %>
      <% end %>
      <%= menu_group pull: :right do %>
        <% if logged_in? %>
          <%= menu_item current_user.email %>
          <%= menu_item "Sign out", sign_out_path %>
        <% else %>
          <%= menu_item "Sign in", sign_in_path %>
        <% end %>
      <% end %>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Become a Brand Ambassador!</h1>

<h4>6 Key Characteristics of a Successful Brand Ambassador</h4>
<p>Think about the last time a word-of-mouth referral influenced one of your purchasing decisions.
<br/>
<br/>
Maybe a friend shared their love of a subscription service like StitchFix, a co-worker sent you a referral code for free Uber credits, or a neighbor recommended their favorite contractor. Or maybe it was as simple as a friendly suggestion on where to go to dinner. Regardless, you probably acted on the referral, in part, because it came from someone you trusted.
<br/>
<br/>
Now, think about the last time you received a referral and ignored it. What led you to discredit the recommendation? A lack of trust in the person delivering it? The way in which the referral was issued? Generally, when referrals look and feel like generic spam, we tend to tune them out — and rightfully so. In those circumstances, the “referral” feels more like an interruptive ad than an authentic recommendation.
<br/>
<br/>
With that in mind, marketers must ask themselves an important question: Which type of referrals are your brand ambassadors driving for your business?
<br/>
<br/>
If it’s the latter, it’s unlikely your referral marketing program (or any referral software you use to support it) will move the needle. This is why it’s so critical for you to vet and qualify ambassadors — the supporters you’re entrusting to generate referrals — before enlisting them to sing your praises. There’s a science to choosing the right people to represent your brand and, if you manage it properly, you’ll reap the rewards for years to come. If you don’t, it could come back to haunt you.
</p>
<h5><b><em>The Core Traits of a Brand Ambassador</em></b></h5>
<p>So, what does a good brand ambassador look like? How should they act? What should they know? If you’re in the process of assembling an army of passionate brand advocates, here are six key characteristics you should be looking for:</p>
<h6><b>1. Knowledge of (and Appreciation for) Marketing</b></h6>
<p>This isn’t to say your ambassadors and advocates need a marketing degree, but they should have a basic understanding of marketing’s core principles. Specifically, the best ambassadors appreciate the importance of authenticity in modern marketing, and grasp the role that digital marketing and social media play in driving high-quality referrals.</p>
<h6><b>2. An Established Online Presence</b></h6>
<p>This ties back to the first characteristic, but it’s equally important. In order for word-of-mouth marketing to be successful, you need ambassadors to reach as many people as possible, across a variety of channels and platforms. Now, this doesn’t mean an ambassador must have 20,000 Twitter followers or thousands of email contacts to represent your brand. But they should have a well-established online presence and a highly-engaged network.</p>
<h6><b>3. A High Level of Professionalism</b></h6>
<p>While ambassadors won’t be employed by your company, these people will be representing your brand. They’ll be talking about your company, encouraging others to check out your products and services, and influencing how others perceive your business. If someone embarrassed themselves or your brand, you’d never hire them, right? The same standards should be applied to your brand ambassadors.</p>
<h6><b>4. Natural Leadership Skills</b></h6>
<p>Think about the people you look to for recommendations. Sure, they’re knowledgeable experts in a particular space, but you probably seek out their opinions because they also exude confidence and positivity — traits that draw you in and make you want to listen. These are the same types of people you want representing your brand in the marketplace.</p>
<h6><b>5. A Passion for Building and Growing Relationships</b></h6>
<p>Ambassadors are not salespeople heading out to make as many one-time sales as possible. They exist to foster strong, loyal relationships between your customers and your brand. Your ambassadors should not only be passionate about — and intimately familiar with — your products or services, they should also be skilled at making deep connections with others on your behalf.</p>
<h6><b>6. The Ability to Gather Feedback and Provide Innovative Insight</b></h6>
<p>No loyalty program is perfect. Neither is any particular product or service. Inevitably, brand ambassadors will gather feedback based on their experience with your product or services, as well as their conversations with your customers and competitors. This information can provide critical intelligence that helps you improve your referral marketing program (and, more broadly, your business).</p>

app/views/pages/home.html.erb
<h2>Brand Ambassador</h2>

<p>© <%= Date.today.year %> Team7media</p>

app/views/real_accounts/_form.html.erb
<%= form_for @real_account, :html => { :class => "form-horizontal real_account" } do |f| %>

  <% if @real_account.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@real_account.errors.count, "error") %> prohibited this real_account from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @real_account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :startdate, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :startdate, :class => 'form-control' %>
    </div>
    <%=f.error_span(:startdate) %>
  </div>
  <div class="form-group">
    <%= f.label :ip, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :ip, :class => 'form-control' %>
    </div>
    <%=f.error_span(:ip) %>
  </div>
  <div class="form-group">
    <%= f.label :firstname, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :firstname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:firstname) %>
  </div>
  <div class="form-group">
    <%= f.label :lastname, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lastname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lastname) %>
  </div>
  <div class="form-group">
    <%= f.label :fb_email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :fb_email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:fb_email) %>
  </div>
  <div class="form-group">
    <%= f.label :fb_pw, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :fb_pw, :class => 'form-control' %>
    </div>
    <%=f.error_span(:fb_pw) %>
  </div>
  <div class="form-group">
    <%= f.label :fb_profile_link, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :fb_profile_link, :class => 'form-control' %>
    </div>
    <%=f.error_span(:fb_profile_link) %>
  </div>
  <div class="form-group">
    <%= f.label :paypal_email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :paypal_email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:paypal_email) %>
  </div>
  <div class="form-group">
    <%= f.label :referrer_paypal, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :referrer_paypal, :class => 'form-control' %>
    </div>
    <%=f.error_span(:referrer_paypal) %>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone) %>
  </div>
  <div class="form-group">
    <%= f.label :disbursement_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :disbursement_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:disbursement_date) %>
  </div>
  <div class="form-group">
    <%= f.label :disbursement_amount, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :disbursement_amount, :class => 'form-control' %>
    </div>
    <%=f.error_span(:disbursement_amount) %>
  </div>
  <div class="form-group">
    <%= f.label :skype_username, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :skype_username, :class => 'form-control' %>
    </div>
    <%=f.error_span(:skype_username) %>
  </div>
  <div class="form-group">
    <%= f.label :notes, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :notes, :class => 'form-control' %>
    </div>
    <%=f.error_span(:notes) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                real_accounts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/real_accounts/edit.html.erb
<%- model_class = RealAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/real_accounts/index.html.erb
<%- model_class = RealAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:startdate) %></th>
      <th><%= model_class.human_attribute_name(:ip) %></th>
      <th><%= model_class.human_attribute_name(:firstname) %></th>
      <th><%= model_class.human_attribute_name(:lastname) %></th>
      <th><%= model_class.human_attribute_name(:fb_email) %></th>
      <th><%= model_class.human_attribute_name(:fb_pw) %></th>
      <th><%= model_class.human_attribute_name(:fb_profile_link) %></th>
      <th><%= model_class.human_attribute_name(:paypal_email) %></th>
      <th><%= model_class.human_attribute_name(:referrer_paypal) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:disbursement_date) %></th>
      <th><%= model_class.human_attribute_name(:disbursement_amount) %></th>
      <th><%= model_class.human_attribute_name(:skype_username) %></th>
      <th><%= model_class.human_attribute_name(:notes) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @real_accounts.each do |real_account| %>
      <tr>
        <td><%= link_to real_account.id, real_account_path(real_account) %></td>
        <td><%= real_account.startdate %></td>
        <td><%= real_account.ip %></td>
        <td><%= real_account.firstname %></td>
        <td><%= real_account.lastname %></td>
        <td><%= real_account.fb_email %></td>
        <td><%= real_account.fb_pw %></td>
        <td><%= real_account.fb_profile_link %></td>
        <td><%= real_account.paypal_email %></td>
        <td><%= real_account.referrer_paypal %></td>
        <td><%= real_account.phone %></td>
        <td><%= real_account.disbursement_date %></td>
        <td><%= real_account.disbursement_amount %></td>
        <td><%= real_account.skype_username %></td>
        <td><%= real_account.notes %></td>
        <td><%=l real_account.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      real_account_path(real_account), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_real_account_path(real_account), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      real_account_path(real_account),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_real_account_path,
            :class => 'btn btn-primary' %>

app/views/real_accounts/new.html.erb
<%- model_class = RealAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/real_accounts/show.html.erb
<%- model_class = RealAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:startdate) %>:</strong></dt>
  <dd><%= @real_account.startdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ip) %>:</strong></dt>
  <dd><%= @real_account.ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:firstname) %>:</strong></dt>
  <dd><%= @real_account.firstname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lastname) %>:</strong></dt>
  <dd><%= @real_account.lastname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fb_email) %>:</strong></dt>
  <dd><%= @real_account.fb_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fb_pw) %>:</strong></dt>
  <dd><%= @real_account.fb_pw %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fb_profile_link) %>:</strong></dt>
  <dd><%= @real_account.fb_profile_link %></dd>
  <dt><strong><%= model_class.human_attribute_name(:paypal_email) %>:</strong></dt>
  <dd><%= @real_account.paypal_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:referrer_paypal) %>:</strong></dt>
  <dd><%= @real_account.referrer_paypal %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @real_account.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:disbursement_date) %>:</strong></dt>
  <dd><%= @real_account.disbursement_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:disbursement_amount) %>:</strong></dt>
  <dd><%= @real_account.disbursement_amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:skype_username) %>:</strong></dt>
  <dd><%= @real_account.skype_username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:notes) %>:</strong></dt>
  <dd><%= @real_account.notes %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              real_accounts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_real_account_path(@real_account), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              real_account_path(@real_account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/smurves/_form.html.erb
<%= form_for @smurf, :html => { :class => "form-horizontal smurf" } do |f| %>

  <% if @smurf.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@smurf.errors.count, "error") %> prohibited this smurf from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @smurf.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :startdate, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :startdate, :class => 'form-control' %>
    </div>
    <%=f.error_span(:startdate) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :status, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label :ip, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :ip, :class => 'form-control' %>
    </div>
    <%=f.error_span(:ip) %>
  </div>
  <div class="form-group">
    <%= f.label :firstname, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :firstname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:firstname) %>
  </div>
  <div class="form-group">
    <%= f.label :lastname, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lastname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lastname) %>
  </div>
  <div class="form-group">
    <%= f.label :login, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :login, :class => 'form-control' %>
    </div>
    <%=f.error_span(:login) %>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password) %>
  </div>
  <div class="form-group">
    <%= f.label :cardtype, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cardtype, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cardtype) %>
  </div>
  <div class="form-group">
    <%= f.label :creditcardnumber, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :creditcardnumber, :class => 'form-control' %>
    </div>
    <%=f.error_span(:creditcardnumber) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :paypalemail, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :paypalemail, :class => 'form-control' %>
    </div>
    <%=f.error_span(:paypalemail) %>
  </div>
  <div class="form-group">
    <%= f.label :notes, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :notes, :class => 'form-control' %>
    </div>
    <%=f.error_span(:notes) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                smurves_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/smurves/edit.html.erb
<%- model_class = Smurf -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/smurves/new.html.erb
<%- model_class = Smurf -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>